

export 'dart:async';
export 'dart:convert';
export 'dart:io';

export 'package:another_xlider/another_xlider.dart';
export 'package:another_xlider/models/handler.dart';
export 'package:another_xlider/models/tooltip/tooltip.dart';
export 'package:another_xlider/models/trackbar.dart';
export 'package:colorful_safe_area/colorful_safe_area.dart';
export 'package:coupon_uikit/coupon_uikit.dart';
export 'package:device_info_plus/device_info_plus.dart';
/*============================================ third parties libraries ====================================*/

export 'package:dio/dio.dart';
export 'package:dotted_border/dotted_border.dart';
export 'package:fancy_shimmer_image/fancy_shimmer_image.dart';
export 'package:fdottedline_nullsafety/fdottedline__nullsafety.dart';
export 'package:file_picker/file_picker.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:flutter/cupertino.dart' hide RefreshCallback;
export 'package:flutter/foundation.dart';
/* =============================================dart, flutter and getx =====================================*/

export 'package:flutter/gestures.dart';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:flutter_animate/flutter_animate.dart'
    hide ScaleEffect, SwapEffect, SlideEffect;
export 'package:flutter_dash/flutter_dash.dart';
export 'package:flutter_easyloading/flutter_easyloading.dart';
export 'package:flutter_rating_bar/flutter_rating_bar.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
/*================================================== application binding =====================================*/

export 'package:base_project/app/bindings/initial_binding.dart';
export 'package:base_project/app/bindings/local_source_bindings.dart';
export 'package:base_project/app/bindings/repository_bindings.dart';
/*=============================================== base exports =============================================*/

export 'package:base_project/app/core/base/base_view.dart';
export 'package:base_project/app/core/base/page_state.dart';
export 'package:base_project/app/core/translations/language/en_US.dart';
export 'package:base_project/app/core/translations/language/zn_CH.dart';
/* ================================================Translations ===========================================*/
export 'package:base_project/app/core/translations/local_keys.dart';
export 'package:base_project/app/core/translations/translation_service.dart';
export 'package:base_project/app/core/utils/card_utility.dart';
export 'package:base_project/app/core/utils/common_methods.dart';
export 'package:base_project/app/core/utils/common_video_player.dart';
export 'package:base_project/app/core/utils/current_location_provider.dart';
export 'package:base_project/app/core/utils/debouncer.dart';
export 'package:base_project/app/core/utils/distance_provider.dart';
export 'package:base_project/app/core/utils/helper_widget.dart';
export 'package:base_project/app/core/utils/image_picker.dart';
export 'package:base_project/app/core/utils/show_place_picker.dart';
export 'package:base_project/app/core/utils/url_launcher.dart';
export 'package:base_project/app/core/utils/validator.dart';
export 'package:base_project/app/core/values/app_assets.dart';
export 'package:base_project/app/core/values/app_colors.dart';
export 'package:base_project/app/core/values/app_constants.dart';
export 'package:base_project/app/core/values/app_global_values.dart';
export 'package:base_project/app/core/values/app_theme.dart';
/* ================================================app constants ===========================================*/

export 'package:base_project/app/core/values/app_values.dart';
export 'package:base_project/app/core/values/route_arguments.dart';
export 'package:base_project/app/core/values/text_styles.dart';
export 'package:base_project/app/core/widget/alert_dialog_widget.dart';
export 'package:base_project/app/core/widget/annotated_region_widget.dart';
export 'package:base_project/app/core/widget/asset_image.dart';
export 'package:base_project/app/core/widget/bounce_widget.dart';
export 'package:base_project/app/core/widget/button_widget.dart';
export 'package:base_project/app/core/widget/custom_appbar.dart';
export 'package:base_project/app/core/widget/custom_flashbar.dart';
export 'package:base_project/app/core/widget/custom_inkwell.dart';
export 'package:base_project/app/core/widget/custom_loader.dart';
export 'package:base_project/app/core/widget/double_back_press.dart';
/*=================================================== widgets =============================================*/

export 'package:base_project/app/core/widget/edit_text_widget.dart';
export 'package:base_project/app/core/widget/image_picker_dialog.dart';
export 'package:base_project/app/core/widget/images_videos_widget.dart';
export 'package:base_project/app/core/widget/logout_dialog.dart';
export 'package:base_project/app/core/widget/mask_formatter.dart';
export 'package:base_project/app/core/widget/network_image.dart';
export 'package:base_project/app/core/widget/no_result_found_widget.dart';
export 'package:base_project/app/core/widget/out_of_stock_not_available.dart';
export 'package:base_project/app/core/widget/read_more_widget.dart';
export 'package:base_project/app/core/widget/screen_heading.dart';
export 'package:base_project/app/core/widget/stepper/country_picker.dart';
export 'package:base_project/app/core/widget/stepper/dot_provider.dart';
export 'package:base_project/app/core/widget/stepper/stepper_model.dart';
export 'package:base_project/app/core/widget/stepper/stepper_widget.dart';
export 'package:base_project/app/core/widget/stepper/ticket_painter_widget.dart';
export 'package:base_project/app/core/widget/stepper/ticket_widget.dart';
export 'package:base_project/app/core/widget/text_field_dialog_widget.dart';
export 'package:base_project/app/core/widget/text_view.dart';
export 'package:base_project/app/core/widget/time_formatter.dart';
/*==================================================== local services =====================================*/

export 'package:base_project/app/data/local/prefrences/preference.dart';
export 'package:base_project/app/data/models/error_response_model.dart';
export 'package:base_project/app/data/models/google_response_models/google_time_response_model.dart';
export 'package:base_project/app/data/models/links_self_meta_model.dart';
/* =========================================== response model=====================================================*/

export 'package:base_project/app/data/models/message_response_model.dart';
// notifications and firebase
export 'package:base_project/app/data/push_notification_manager.dart';
/*================================================== dio client ======================================*/

export 'package:base_project/app/data/repository/api_repository.dart';
/* =========================================== request model=====================================================*/

export 'package:base_project/app/data/repository/auth_request_model.dart';
export 'package:base_project/app/data/repository/dio_client.dart';
export 'package:base_project/app/data/repository/endpoint.dart';
export 'package:base_project/app/data/repository/network_exceptions.dart';
export 'package:base_project/app/export.dart';
export 'package:base_project/app/logger/logger_utils.dart';
export 'package:base_project/app/modules/authentication/bindings/change_password_binding.dart';
export 'package:base_project/app/modules/authentication/bindings/forgot_password_binding.dart';
export 'package:base_project/app/modules/authentication/bindings/forgot_password_options_binding.dart';
export 'package:base_project/app/modules/authentication/bindings/login_binding.dart';
export 'package:base_project/app/modules/authentication/bindings/otp_verification_binding.dart';
export 'package:base_project/app/modules/authentication/bindings/signup_binding.dart';
export 'package:base_project/app/modules/authentication/controllers/change_password_controller.dart';
export 'package:base_project/app/modules/authentication/controllers/forgot_password_controller.dart';
export 'package:base_project/app/modules/authentication/controllers/login_controller.dart';
export 'package:base_project/app/modules/authentication/controllers/otp_verification_controller.dart';
export 'package:base_project/app/modules/authentication/controllers/signup_controller.dart';
export 'package:base_project/app/modules/authentication/models/data_model/media_file_model.dart';
export 'package:base_project/app/modules/authentication/models/data_model/shop_rest_availability_model.dart';
export 'package:base_project/app/modules/authentication/models/data_model/store_rest_data_model.dart';
export 'package:base_project/app/modules/authentication/models/data_model/user_data_model.dart';
export 'package:base_project/app/modules/authentication/models/data_model/vehicle_data_model.dart';
export 'package:base_project/app/modules/authentication/models/request_data_model/RememberMeModel.dart';
export 'package:base_project/app/modules/authentication/models/request_data_model/merchant_request_models.dart';
export 'package:base_project/app/modules/authentication/models/response_models/common_message_response_model.dart';
export 'package:base_project/app/modules/authentication/models/response_models/rest_store_response_model.dart';
export 'package:base_project/app/modules/authentication/models/response_models/user_data_model.dart';
export 'package:base_project/app/modules/authentication/models/response_models/vehicle_response_model.dart';
//Restaurant

export 'package:base_project/app/modules/authentication/views/change_password_screen.dart';
export 'package:base_project/app/modules/authentication/views/forgot_password_options.dart';
export 'package:base_project/app/modules/authentication/views/forgot_password_screen.dart';
export 'package:base_project/app/modules/authentication/views/login_screen.dart';
export 'package:base_project/app/modules/authentication/views/otp_verification_screen.dart';
export 'package:base_project/app/modules/authentication/views/signup_screen.dart';
export 'package:base_project/app/modules/authentication/widgets/authentication_screen_heading.dart';
export 'package:base_project/app/modules/chat/bindings/chat_bindings.dart';
export 'package:base_project/app/modules/chat/models/data_models/chat_data_model.dart';
export 'package:base_project/app/modules/chat/models/responseModels/chat_list_response_model.dart';
export 'package:base_project/app/modules/chat/views/chat_screen.dart';
export 'package:base_project/app/modules/chat/views/life_needs_chat_list_screen.dart';
// export 'package:base_project/app/modules/customer/common_models/buy_item_cart_model.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/bindings/customer_life_needs_binding.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/life_need_post_view_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/life_needs_comment_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/life_needs_create_post_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/life_needs_home_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/life_needs_profile_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/life_needs_user_posts_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/my_posts_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/order_delivered_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/controllers/post_details_controller.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/data_models/comment_data_model.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/data_models/liked_by_data_model.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/data_models/post_model.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/request_models/request_models.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/response_models/comments_list_response_model.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/response_models/post_detail_response_model.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/response_models/post_like_dislike_response.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/models/response_models/post_list_response_model.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/life_need_post_view.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/life_needs_comment_screen.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/life_needs_create_post_screen.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/life_needs_home_screen.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/life_needs_profile_screen.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/life_needs_user_posts_screen.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/my_posts_screen.dart';
// export 'package:base_project/app/modules/customer/customer_life_needs/views/post_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/bindings/address_list_binding.dart';
// export 'package:base_project/app/modules/customer/home/bindings/cloud_family_bindings.dart';
//Customer
// export 'package:base_project/app/modules/customer/home/bindings/customer_home_binding.dart';
// export 'package:base_project/app/modules/customer/home/bindings/leg_running_binding.dart';
// export 'package:base_project/app/modules/customer/home/bindings/mart_detail_bindings.dart';
// export 'package:base_project/app/modules/customer/home/bindings/rest_detail_bindings.dart';
// export 'package:base_project/app/modules/customer/home/bindings/successful_order_binding.dart';
// export 'package:base_project/app/modules/customer/home/controller/add_to_cart_controller/add_to_cart_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/address_module_cotroller/add_address_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/address_module_cotroller/address_list_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/all_restaurants_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/clooud_family_restaurant_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/cloud_fam_add_item_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/cloud_fam_cart_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/cloud_fam_order_confirm_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/cloud_fam_rest_detail_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/cloud_family_meal_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/cloud_order_type_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/cloud_fam_controllers/plate_detail_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/coupon_detail_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/coupons_list_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_contact_us_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_favourite_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_main_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_orders_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_profile_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_profile_home_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_rate_us_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/customer_track_order_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/filter_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/fresh_foods_products_list_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/index_controller/customer_home_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/index_controller/customer_offers_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/index_controller/popular_dishes_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/index_controller/recommendations_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/leg_running_module/about_package_screen_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/leg_running_module/confirmation_screen_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/leg_running_module/courier_service_screen_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/leg_running_module/leg_runnig_home_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/leg_running_module/leg_running_order_details_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/leg_running_module/receiver_details_screen_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/main_course_detail_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/main_course_screen_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/mart_detail_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/order_cart_controller.dart';
//Driver

//Customer
// export 'package:base_project/app/modules/customer/home/controller/order_confrmation_screen_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/order_detail_map_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/order_details_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/order_now_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/promo_codes_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/restaurant_cloud_family_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/restaurant_detail_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/running_errands_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/search_view_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/store_map_controller.dart';
// export 'package:base_project/app/modules/customer/home/controller/stores_malls_list_controller.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/address_module/address_data_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/cart/cart_data_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/cart/cart_item_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/color_combo.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/favourites/fav_data_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/image_title_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/index/order_recommendation_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/add_on_item_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/cloud_fam_item_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/cloud_fam_plate_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/common_item_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/coupon_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/merchant_item_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/plate_data_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/plate_item_data_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/rest_menu_price_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/items_models/shopMart_price_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/leg_running_data_model/courier_data_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/leg_running_data_model/leg_running_data_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/leg_running_data_model/order_track_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/orders/order_detail_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/orders/order_item_detail_model.dart';
// export 'package:base_project/app/modules/customer/home/model/data_model/orders/order_state_model.dart';
// export 'package:base_project/app/modules/customer/home/model/request_model/add_to_cart_request_model.dart';
// export 'package:base_project/app/modules/customer/home/model/request_model/address_request_model.dart';
// export 'package:base_project/app/modules/customer/home/model/request_model/address_type.dart';
// export 'package:base_project/app/modules/customer/home/model/request_model/leg_running_request_model.dart';
// export 'package:base_project/app/modules/customer/home/model/request_model/order_request_models.dart';
// export 'package:base_project/app/modules/customer/home/model/request_model/ratings_request_models.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/address_module_model/address_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/banner_images_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/cart_response_model/cart_status_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/cart_response_model/my_cart_items_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/common_items_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/favourites/add_to_fav_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/favourites/favourites_list_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/index/images_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/index/order_recommendations_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/index/rest_store_list_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/items_response_model/coupons_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/items_response_model/merchant_item_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/items_response_model/plate_detail_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/items_response_model/plate_item_detail_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/items_response_model/plate_items_lits_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/items_response_model/plates_list_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/items_response_model/single_rest_menu_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/leg_running_response_model/courier_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/leg_running_response_model/couriers_list_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/leg_running_response_model/service_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/orders/order_detail_response_model.dart';
// export 'package:base_project/app/modules/customer/home/model/response_model/orders/orders_list_response_model.dart';
// export 'package:base_project/app/modules/customer/home/views/add_to_cart/add_to_card_widget.dart';
// export 'package:base_project/app/modules/customer/home/views/address_module/add_address_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/address_module/address_list_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/all_restaurants_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/categories/categories_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/cloud_fam_add_item_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/cloud_fam_cart_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/cloud_fam_order_confirm_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/cloud_fam_rest_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/cloud_family_meal_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/cloud_family_restaurant_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/cloud_order_type_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/cloud_family/customer_plate_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/coupon_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/coupons_list_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_contact_us_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_favourite_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_main_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_orders_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_profile_home_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_profile_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_rate_us_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/customer_track_order_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/edit_profile_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/filter_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/fresh_foods_products_list_screen.dart';
//Customer
// export 'package:base_project/app/modules/customer/home/views/index/customer_home_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/index/customer_offers_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/index/order_recommendations_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/index/popular_dishes_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/leg_running/about_package_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/leg_running/confirmation_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/leg_running/courier_service_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/leg_running/leg_runnig_home_page.dart';
// export 'package:base_project/app/modules/customer/home/views/leg_running/leg_running_order_details.dart';
// export 'package:base_project/app/modules/customer/home/views/leg_running/receiver_details_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/main_course_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/main_course_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/mart_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/order_cart_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/order_delivered_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/order_detail_map_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/order_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/order_now_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/promo_codes_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/restaurant_cloud_family_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/restaurant_detail_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/running_errands_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/search_view_screen.dart';
// export 'package:base_project/app/modules/customer/home/views/store_map_view.dart';
// export 'package:base_project/app/modules/customer/home/views/stores_malls_list_screen.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/bindings/video_tutoring_binding.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/controllers/video_tutoring_choose_your_courses_controller.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/controllers/video_tutoring_controller.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/controllers/video_tutoring_course_details_controller.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/controllers/video_tutoring_my_courses_controller.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/controllers/video_tutoring_my_courses_detail_controller.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/models/data_models/course_data_model.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/models/data_models/course_video_model.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/models/data_models/my_course_model.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/models/request_models/vide_tut_request_models.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/models/response_models/courses_list_response_model.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/models/response_models/my_courses_list_response_model.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/views/video_tutoring_choose_your_courses_screen.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/views/video_tutoring_course_details_screen.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/views/video_tutoring_home.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/views/video_tutoring_my_course_detail_screen.dart';
// export 'package:base_project/app/modules/customer/video_tutoring/views/video_tutoring_my_courses_screen.dart';
// export 'package:base_project/app/modules/customer/widgets/course_view_widget.dart';
// export 'package:base_project/app/modules/customer/widgets/customer_app_bar_widget.dart';
// export 'package:base_project/app/modules/customer/widgets/restaraunt_item_view.dart';
// export 'package:base_project/app/modules/map_view_widget/bindings/map_view_bindings.dart';
// export 'package:base_project/app/modules/map_view_widget/controllers/map_view_controller.dart';
// export 'package:base_project/app/modules/map_view_widget/views/map_view_screen.dart';
export 'package:base_project/app/modules/notification/bindings/notification_binding.dart';
export 'package:base_project/app/modules/notification/controllers/notification_controller.dart';
export 'package:base_project/app/modules/notification/models/dataModels/notification_data_model.dart';
export 'package:base_project/app/modules/notification/models/responseModels/notification_list_response_model.dart';
export 'package:base_project/app/modules/notification/views/notification_screen.dart';
// export 'package:base_project/app/modules/payment/bindings/payment_binding.dart';
// export 'package:base_project/app/modules/payment/controllers/add_bank_account_controller.dart';
// export 'package:base_project/app/modules/payment/controllers/payment_controller.dart';
// export 'package:base_project/app/modules/payment/controllers/payment_successful_controller.dart';
// export 'package:base_project/app/modules/payment/models/dataModels/card_data_model.dart';
// export 'package:base_project/app/modules/payment/models/dataModels/payment_method_model.dart';
// export 'package:base_project/app/modules/payment/models/payment_request_model.dart';
// export 'package:base_project/app/modules/payment/models/responseModel/card_list_response_model.dart';
// export 'package:base_project/app/modules/payment/views/add_bank_account_screen.dart';
// export 'package:base_project/app/modules/payment/views/payment_screen.dart';
// export 'package:base_project/app/modules/payment/views/payment_successful_screen.dart';
// export 'package:base_project/app/modules/ratings/bindings/rating_review_binding.dart';
// export 'package:base_project/app/modules/ratings/bindings/referral_binding.dart';
// export 'package:base_project/app/modules/ratings/controllers/rating_review_controller.dart';
// export 'package:base_project/app/modules/ratings/controllers/referral_controller.dart';
// export 'package:base_project/app/modules/ratings/models/data_models/rating_count_model.dart';
// export 'package:base_project/app/modules/ratings/models/data_models/rating_model.dart';
// export 'package:base_project/app/modules/ratings/models/response_models/driver_ratings_response_model.dart';
// export 'package:base_project/app/modules/ratings/models/response_models/ratings_response_model.dart';
// export 'package:base_project/app/modules/ratings/views/rating_review_screen.dart';
// export 'package:base_project/app/modules/ratings/views/referral_screen.dart';
// export 'package:base_project/app/modules/roleSelection/bindings/role_selection_binding.dart';
// export 'package:base_project/app/modules/roleSelection/controllers/role_selection_controller.dart';
// export 'package:base_project/app/modules/roleSelection/views/role_selection_screen.dart';
export 'package:base_project/app/modules/splash/bindings/on_boarding_binding.dart';
export 'package:base_project/app/modules/splash/bindings/splash_binding.dart';
export 'package:base_project/app/modules/splash/controllers/on_boarding_controller.dart';
/*============================================== application controllers =====================================*/

export 'package:base_project/app/modules/splash/controllers/splash_controller.dart';
export 'package:base_project/app/modules/splash/views/on_boarding_screen.dart';
export 'package:base_project/app/modules/splash/views/splash_screen.dart';
/* =========================================== application widgets=====================================================*/

export 'package:base_project/app/modules/splash/widgets/on_boarding_widget.dart';
export 'package:base_project/app/modules/staticPages/bindings/faq_binding.dart';
export 'package:base_project/app/modules/staticPages/bindings/others_binding.dart';
export 'package:base_project/app/modules/staticPages/bindings/static_page_binding.dart';
export 'package:base_project/app/modules/staticPages/controllers/faq_controller.dart';
export 'package:base_project/app/modules/staticPages/controllers/others_controller.dart';
export 'package:base_project/app/modules/staticPages/controllers/static_page_controller.dart';
export 'package:base_project/app/modules/staticPages/models/faq_response_model.dart';
export 'package:base_project/app/modules/staticPages/models/static_page_response_model.dart';
export 'package:base_project/app/modules/staticPages/views/faq_screen.dart';
export 'package:base_project/app/modules/staticPages/views/other_screen.dart';
export 'package:base_project/app/modules/staticPages/views/static_page_screen.dart';
/* ==================================================app routes ===========================================*/

export 'package:base_project/app/routes/app_pages.dart';
export 'package:base_project/app/routes/app_routes.dart';
export 'package:base_project/main.dart';
/*============================================== application screens =====================================*/
export 'package:base_project/my_app.dart';
export 'package:get/get.dart'
    hide Response, HeaderValue, MultipartFile, FormData;
export 'package:get/instance_manager.dart';
export 'package:get_storage/get_storage.dart';
export 'package:grouped_list/grouped_list.dart';
// export 'package:image_cropper/image_cropper.dart';
export 'package:image_picker/image_picker.dart';
export 'package:intl/intl.dart' hide TextDirection;
export 'package:intl_phone_field/countries.dart';
export 'package:lottie/lottie.dart';
export 'package:media_kit/media_kit.dart';
export 'package:media_kit_video/media_kit_video.dart';
export 'package:mime/mime.dart';
export 'package:navigation_history_observer/navigation_history_observer.dart';
export 'package:package_info_plus/package_info_plus.dart';
export 'package:path_provider/path_provider.dart';
export 'package:photo_view/photo_view.dart';
export 'package:pinput/pinput.dart';
export 'package:smooth_page_indicator/smooth_page_indicator.dart';
